#!/usr/bin/env sh
# Load nvm 若存在nvm，则必须先加载nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Load husky library
. "$(dirname -- "$0")/_/husky.sh"


npx lint-staged
# Check the script result
if [ $? -ne 0 ]; then
  echo "Error: 提交的接口有重复声明，请检查完再提交。 "
  exit 1
fi
# If the script passed, continue with the commit
exit 0

# npm run testEs